config/routes.rb
Rails.application.routes.draw do
  get 'token/exchange'
  get 'remember_me/clear_remember_me'
  get '/book_seats/:rsvp_link', to: 'guests#book_seats', as: 'book_seats'
  get '/email_services/new_email_template', to: 'email_services#new_email_template', as: 'new_email_template'
  get '/email_services/email_template/:id', to: 'email_services#edit_email_template', as: 'edit_email_template'
  get '/email_services/render_email_template', to: 'email_services#render_template', as: 'render_email_template'
  get 'destroy_email_template/:id', to: 'email_services#destroy_email_template', as: 'destroy_email_template'

  #get '/referral/:ref_code', to: 'referrals#refer', as: 'referral'

  get '/refer_a_friend/:random_code', to: 'referrals#new', as: 'new_referral'
  post '/refer_a_friend/:random_code', to: 'referrals#referral_creation', as: 'referral_creation'

  get '/buy_tickets', to: 'tickets#new', as: 'new_ticket_purchase'

  resources :email_services do
    member do
      get 'send_email'
      #get 'show'
      #get 'index'
    end
  end

  resources :events do
    resources :referrals, only: [:new, :referral_creation, :edit, :update]
  end

  resources :tickets, only: [:new, :create]

  post '/import_guests_csv', to: 'guests#import_guests_csv'# Defines a route for the upload_existing_plan action on guests controller.

  resources :guests do
    collection do
      post '/import_guests_csv', to: 'guests#import_guests_csv'
      get :import
      post :import, to: 'guests#process_import'
      get :new_guest, to: 'guests#new_guest'
    end
  end
  
  resources :events do
    resources :guests do
      collection do
        post 'import_csv', to: 'guests#import_guests_csv', as: 'import_csv'
      end
    end
  end

  
  root 'home#index'

  post 'email_services/add_email_template', to: 'email_services#add_email_template', as: 'add_email_template'
  patch '/email_services/email_template/:id/update', to: 'email_services#update_email_template', as: 'update_email_template'
  patch '/update_commited_seats/:rsvp_link', to: 'guests#update_commited_seats', as: 'update_commited_seats'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
    post 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
  end

  resources :events do
    resources :seats
    resources :guests
  end

  #resources :seats
  #resources :guests
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :event
  
  
  # ===================================
  # required to have to pass Rspec tests
  validates :category, presence: true
  validates :section, presence: true
  validates :total_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # ===================================
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  # <!--===================-->
  # <!--corresponding filter of the defined method for nested scaffold-->
  before_action :get_event
  # <!--===================-->
  
  
  before_action :set_seat, only: %i[ show edit update destroy ]

  # GET /seats or /seats.json
  def index
    # @seats = Seat.all
    
    # <!--===================-->
    # <!--to return all children instances associated with a particular parent instance-->
    @seats = @event.seats
    # <!--===================-->
  end

  # GET /seats/1 or /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    # @seat = Seat.new
    
    # <!--===================-->
    # <!--to create a child object that’s associated with the specific parent instance -->
    @seat = @event.seats.build
    # <!--===================-->
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats or /seats.json
  def create
    # @seat = Seat.new(seat_params)
    #puts "=== Creating Seat ==="
    #Rails.logger.debug(params.inspect)
    # <!--===================-->
    # <!--to post a new child instance-->
    @seat = @event.seats.build(seat_params)
    # <!--===================-->

    respond_to do |format|
      if @seat.save
        # format.html { redirect_to seat_url(@seat), notice: "Seat was successfully created." }
        format.html { redirect_to event_url(@event), notice: "Seat was successfully created." }
        format.json { render :show, status: :created, location: @seat }
      else
        #Rails.logger.debug(@seat.errors.inspect)
        #puts "Errors: #{@seat.errors.inspect}"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1 or /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        # format.html { redirect_to seat_url(@seat), notice: "Seat was successfully updated." }
        format.html { redirect_to event_seat_path(@event), notice: "Seat was successfully updated." }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1 or /seats/1.json
  def destroy
    @seat.destroy

    respond_to do |format|
      # format.html { redirect_to seats_url, notice: "Seat was successfully destroyed." }
      format.html { redirect_to event_seats_path(@event), notice: "Seat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    # <!--===================-->
    # <!--to create a local @child instance variable-->
    def get_event
      @event = Event.find(params[:event_id])
    end
    # <!--===================-->
    
    
    
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      # @seat = Seat.find(params[:id])
      
      # <!--===================-->
      # <!--to search for a matching id in the collection of children associated with a particular parent-->
      @seat = @event.seats.find(params[:id])
      # <!--===================-->
    end

    # Only allow a list of trusted parameters through.
    def seat_params
      params.require(:seat).permit(:category, :section, :total_count, :event_id)
    end
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%# following changes are made:
        - Changed the first line to reflect the relationship between parent and child resources:
        - deleted the section that lists the parent_id of the related parent, 
          since this is not essential information in the view. %>

<div style="display: flex; justify-content: center; align-items: center;">
<%= form_with(model: [@event, seat]) do |form| %>
  <% if seat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
        <% seat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div style="margin-bottom: 10px;">
    <%= form.label :category, style: "display: block;" %>
    <%= form.text_field :category, style: "width: 100%; padding: 5px; border: 1px solid #ccc; border-radius: 5px;" %>
  </div>

  <div style="margin-bottom: 10px;">
    <%= form.label :section, style: "display: block;" %>
    <%= form.text_field :section, style: "width: 100%; padding: 5px; border: 1px solid #ccc; border-radius: 5px;" %>
  </div>

  <div style="margin-bottom: 10px;">
    <%= form.label :total_count, style: "display: block;" %>
    <%= form.number_field :total_count, style: "width: 100%; padding: 5px; border: 1px solid #ccc; border-radius: 5px;" %>
  </div>

  <div>
    <%= form.submit style: "width: 100%; padding: 10px; background-color: #4caf50; color: white; border: none; border-radius: 5px;" %>
  </div>
<% end %>
</div>

app/views/seats/_seat.html.erb
<%# following changes are made:
        - deleted the section that lists the parent_id of the related parent, 
        since this is not essential information in the view. %>


<div id="<%= dom_id seat %>">
  <table style="width: 300px; table-layout: fixed;border: 1px solid #ccc; border-collapse: collapse; text-align: left;">
   <tr>
      <td style="padding: 10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= seat.category %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc;"><%= seat.total_count %></td>
    </tr>
  </table>
</div>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%# link_to "Show this seat", @seat %>
  <%= link_to "Show this seat", [@event, @seat] %> |
  <%# link_to "Back to seats", seats_path %>
  <%= link_to "Back to seats", event_seats_path(@event) %>
</div>

app/views/seats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Seats</h1>

<div id="seats">
  <% @seats.each do |seat| %>
    <%= render seat %>
    <p>
      <%# link_to "Show this seat", seat %>
      <%= link_to "Show this seat", [@event, seat] %>
    </p>
  <% end %>
</div>

<%# link_to "New seat", new_seat_path %>
<%= link_to "New seat", new_event_seat_path(@event) %> |

<%= link_to "Back to event", event_path(@event) %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%# link_to "Back to seats", seats_path %>
  <%= link_to "Back to seats", event_seats_path(@event) %>
</div>

app/views/seats/show.html.erb
<p style="color: green"><%= notice %></p>

<table style="width: 300px; border: 1px solid #ccc;margin-left:31%;margin-top:5%">
  <tr style="background-color: #f2f2f2;">
    <th style="padding: 10px; border-bottom: 1px solid #ccc;">Category</th>
    <th style="padding: 10px; border-bottom: 1px solid #ccc;">Total Count</th>
  </tr>
</table>

<div style="display: flex; justify-content: center; align-items: center;margin-top:-50px">
<%= render @seat %>

<div style="display: flex;flex-direction: column;margin-right:100px">
  <%# link_to "Edit this seat", edit_seat_path(@seat) %>
  <%# link_to "Edit this seat", edit_event_seat_path(@event, seat) %>
  <%= link_to "Edit this seat", edit_event_seat_path(@event, @seat), style: 'display: inline-block; padding: 10px 20px; background-color: #007bff; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;margin-bottom: 10px;margin-top:10px;margin-left:20px', class: 'button' %>
  <%# link_to "Back to seats", seats_path %>
  <%= link_to "Back to seats", event_seats_path(@event), style: 'display: inline-block; padding: 10px 20px; background-color: #007bff; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;margin-bottom:10px;margin-top:10px;margin-left:20px', class: 'button' %>

  <%# button_to "Destroy this seat", @seat, method: :delete %>
  <%# button_to "Destroy this seat", [@event, seat], method: :delete %>
  <%= button_to "Destroy this seat", [@event, @seat], method: :delete, style: 'display: inline-block; padding: 10px 20px; background-color: #dc3545; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;margin-top:10px;margin-left:20px', class: 'button' %>
</div>
</div>