config/routes.rb
Rails.application.routes.draw do
  get 'token/exchange'
  get 'remember_me/clear_remember_me'
  get '/book_seats/:rsvp_link', to: 'guests#book_seats', as: 'book_seats'
  get '/email_services/new_email_template', to: 'email_services#new_email_template', as: 'new_email_template'
  get '/email_services/email_template/:id', to: 'email_services#edit_email_template', as: 'edit_email_template'
  get '/email_services/render_email_template', to: 'email_services#render_template', as: 'render_email_template'
  get 'destroy_email_template/:id', to: 'email_services#destroy_email_template', as: 'destroy_email_template'

  #get '/referral/:ref_code', to: 'referrals#refer', as: 'referral'

  get '/refer_a_friend/:random_code', to: 'referrals#new', as: 'new_referral'
  post '/refer_a_friend/:random_code', to: 'referrals#referral_creation', as: 'referral_creation'

  get '/buy_tickets', to: 'tickets#new', as: 'new_ticket_purchase'

  resources :email_services do
    member do
      get 'send_email'
      #get 'show'
      #get 'index'
    end
  end

  resources :events do
    resources :referrals, only: [:new, :referral_creation, :edit, :update]
  end

  resources :tickets, only: [:new, :create]

  post '/import_guests_csv', to: 'guests#import_guests_csv'# Defines a route for the upload_existing_plan action on guests controller.

  resources :guests do
    collection do
      post '/import_guests_csv', to: 'guests#import_guests_csv'
      get :import
      post :import, to: 'guests#process_import'
      get :new_guest, to: 'guests#new_guest'
    end
  end
  
  resources :events do
    resources :guests do
      collection do
        post 'import_csv', to: 'guests#import_guests_csv', as: 'import_csv'
      end
    end
  end

  
  root 'home#index'

  post 'email_services/add_email_template', to: 'email_services#add_email_template', as: 'add_email_template'
  patch '/email_services/email_template/:id/update', to: 'email_services#update_email_template', as: 'update_email_template'
  patch '/update_commited_seats/:rsvp_link', to: 'guests#update_commited_seats', as: 'update_commited_seats'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
    post 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
  end

  resources :events do
    resources :seats
    resources :guests
  end

  #resources :seats
  #resources :guests
end

app/models/guest.rb
class Guest < ApplicationRecord
  require 'roo'

  belongs_to :event
  has_many :referrals, dependent: :destroy
  
  before_create :generate_rsvp_link
  
  # ===================================
  # required to have to pass Rspec tests
  validates :first_name, presence: true
  validates :last_name, presence: true
  # Removed the email validation
  validates :affiliation, presence: true
  validates :category, presence: true
  validates :event_id, presence: true
  validates :alloted_seats, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :commited_seats, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :guest_commited, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :allocated_seats_not_exceed_total

  def self.new_guest(attributes = {})
    puts "Creating guest with data: first_name=#{attributes[:first_name]}, last_name=#{attributes[:last_name]}, event_id=#{attributes[:event_id]}"
    guest = Guest.new(attributes) #creates new guest
    guest#return guest
  end
  
  def checked_only_if_booked
    return if (booked || !checked)
    errors.add(:checked, "can't be true if guest hasn't booked")
  end

  def full_name
    "#{first_name} #{last_name}"
  end 
  
  
  def allocated_seats_not_exceed_total
    if category.present? && event.present?
      seat = event.seats.find_by(category: category)
      if seat.present?
        existing_guest = event.guests.find_by(id: self.id)
        if existing_guest.present?
          total_allocated_seats = event.guests.where(category: category).sum(:alloted_seats) - existing_guest.alloted_seats.to_i
          total_commited_seats = event.guests.where(category: category).sum(:commited_seats) - existing_guest.commited_seats.to_i
        else
          total_allocated_seats = event.guests.where(category: category).sum(:alloted_seats)
          total_commited_seats = event.guests.where(category: category).sum(:commited_seats)
        end
        remaining_allocated_seats = [0, seat.total_count - total_allocated_seats].max
        remaining_committed_seats = [0, total_allocated_seats + alloted_seats.to_i - total_commited_seats].max

        puts event.guests.where(category: category).sum(:alloted_seats)
        puts total_allocated_seats
        puts alloted_seats.to_i
        puts total_commited_seats
    
        if (total_allocated_seats + alloted_seats.to_i) > seat.total_count
          errors.add(:alloted_seats, "cannot exceed the total allocated seats (#{remaining_allocated_seats} remaining) for the category #{category}")
        end
    
        if (total_commited_seats + commited_seats.to_i) > total_allocated_seats + alloted_seats.to_i
          errors.add(:commited_seats, "cannot exceed the total allocated seats (#{remaining_committed_seats} remaining) for the category #{category}")
        end
      end
    end
    
  end


  # ===================================

  private

  def generate_rsvp_link
    self.rsvp_link = SecureRandom.hex(20) # You can adjust the length as needed
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  require 'csv'
  #<!--===================-->
  # <!--corresponding filter of the defined method for nested scaffold-->
  before_action :get_event, except: [:book_seats, :update_commited_seats]
  # <!--===================-->
  
  before_action :set_guest, only: %i[ show edit update destroy ]

  # GET /guests or /guests.json
  def index
    @guests = @event.guests
  end
  
  # GET /guests/1 or /guests/1.json
  def show
    @guests = Guest.all # or another appropriate query to get the guests
  end

  # GET /guests/new
  def new
    # @guest = Guest.new
    
    # <!--===================-->
    # <!--to create a child object that’s associated with the specific parent instance -->
    @guest = @event.guests.build
    # <!--===================-->
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests or /guests.json
  def create
    # @guest = Guest.new(guest_params)
    
    # <!--===================-->
    # <!--to post a new child instance-->
    @guest = @event.guests.build(guest_params)
    # <!--===================-->

    respond_to do |format|
      if @guest.save
        # format.html { redirect_to guest_url(@guest), notice: "Guest was successfully created." }
        format.html { redirect_to event_url(@event), notice: "Guest was successfully created." }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1 or /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        # format.html { redirect_to guest_url(@guest), notice: "Guest was successfully updated." }
        format.html { redirect_to event_path(@event), notice: "Guest was successfully updated." }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /guests/1 or /guests/1.json
  def destroy
    @guest.destroy

    respond_to do |format|
      # format.html { redirect_to guests_url, notice: "Guest was successfully destroyed." }
      format.html { redirect_to event_guests_path(@event), notice: "Guest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:book_seats, :update_commited_seats]

  def book_seats
    @guest = Guest.find_by(rsvp_link: params[:rsvp_link])

    if @guest
      render 'book_seats'
    else
      render plain: 'Invalid RSVP link', status: :not_found
    end
  end

  def update_commited_seats
    @guest = Guest.find_by(rsvp_link: params[:rsvp_link])
  
    if @guest
      new_commited_seats = params[:guest][:commited_seats].to_i
      total_seats = @guest.commited_seats + new_commited_seats
  
      if total_seats <= @guest.alloted_seats
        @guest.commited_seats = total_seats
  
        if @guest.save
          flash[:notice] = 'Committed seats updated successfully.'
          redirect_to book_seats_path(@guest.rsvp_link)
        else
          render 'book_seats'
        end
      else
        flash[:alert] = 'Error: Total seats exceed allocated seats.'
        render 'book_seats'
      end
    else
      render plain: 'Invalid RSVP link', status: :not_found
    end
  end
  
  def import_guests_csv
    event_id = params[:event_id]
    event = Event.find(event_id)

    return redirect_to event_path(@event), alert: "No file uploaded." if params[:file].blank?

  
    # Roo setup to open the Excel file
    file = params[:file]
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1) # Assuming first row is the header
  
    # Iterate over each row
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
  
      first_name = row["First Name"]
      last_name = row["Last Name"]
      email = row["Email"]
      affiliation = row["Affiliation"] # Ensure this column exists in your Excel file
      category = row["Category"] # Ensure this column exists in your Excel file
      alloted_seats = row["Allotted Seats"].to_i # Adjust the key as per your Excel file
      commited_seats = row["Committed Seats"].to_i # Adjust the key as per your Excel file
      guest_commited = row["Guest Committed"].to_i # Adjust the key as per your Excel file
  
      # Since email is removed, you might want to use a different field to find or initialize guests
      # For example, using first_name and last_name (but ensure these combinations are unique per event)
      guest = Guest.find_or_initialize_by(first_name: first_name, last_name: last_name, event_id: event_id)
      if guest.new_record?
        guest.assign_attributes({
          first_name: first_name,
          last_name: last_name,
          email: email,
          affiliation: affiliation,
          category: category,
          alloted_seats: alloted_seats,
          commited_seats: commited_seats,
          guest_commited: guest_commited
        })
        guest.save!
      end
    end
  
    redirect_to event_path(event), notice: "Guests imported"
  end
  
  private
  
    # <!--===================-->
    # <!--to create a local @child instance variable-->
    def get_event
      @event = Event.find(params[:event_id])
    end
    
    
    # <!--===================-->
    
    
    
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      # @guest = Guest.find(params[:id])
      
      # <!--===================-->
      # <!--to search for a matching id in the collection of children associated with a particular parent-->
      @guest = Guest.find(params[:id])
      # <!--===================-->
    end

    def model_attribute(header)
      case header.downcase
      when 'first name' then 'first_name'
      when 'last name' then 'last_name'
      # Add other mappings as needed
      else header
      end
    end

    # Only allow a list of trusted parameters through.
    def guest_params
      params.require(:guest).permit(:first_name, :last_name, :email, :affiliation, :category, :alloted_seats, :commited_seats, :guest_commited, :status, :event_id)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<style>
  .input-field {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
</style>

<%# following changes are made:
        - Changed the first line to reflect the relationship between parent and child resources:
        - deleted the section that lists the parent_id of the related parent, 
          since this is not essential information in the view. %>


<div class="form-box" style="width: 400px; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 10px;">
<%= form_with(model: [@event, guest]) do |form| %>
  <% if guest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
        <% guest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :Email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  
  <div>
    <%= form.label :affiliation, style: "display: block" %>
    <%= form.text_field :affiliation %>
  </div>

  <div>
      <%= form.label :category, style: "display: block" %>
      <%= form.collection_select :category, @event.seats, :category, :category, prompt: "Select a category" %>
  </div>

  <div>
      <%= form.label :section, style: "display: block" %>
      <%= form.collection_select :section, @event.seats, :section, :section, prompt: "Select a section" %>
  </div>

  <div>
    <%= form.label :alloted_seats, style: "display: block" %>
    <%= form.number_field :alloted_seats %>
  </div>

  <div>
    <%= form.label :commited_seats, style: "display: block" %>
    <%= form.number_field :commited_seats %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/guests/_guest.html.erb
<%# following changes are made:
        - deleted the section that lists the parent_id of the related parent, 
          since this is not essential information in the view. %>

<div id="<%= dom_id guest %>">
  <table style="width: 1000px; table-layout: fixed;border: 1px solid #ccc; border-collapse: collapse; text-align: left;">
   <tr>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.first_name %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.last_name %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.affiliation %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.category %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.alloted_seats %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.commited_seats %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.guest_commited %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= guest.status %></td>
      <td style="padding:10px;border-bottom: 1px solid #ccc; border-right: 1px solid #ccc"><%= link_to "Detailsgi", [@event, guest], style: 'display: inline-block; width: 80%; padding: 10px 20px; background-color: #007bff; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;' %></td>
    </tr>
  </table>
</div>

app/views/guests/book_seats.html.erb
<!-- app/views/guests/book_seats.html.erb -->

<h1>Book Seats</h1>

<% if @guest %>
  <h2>Guest Details</h2>
  <p>Name: <%= @guest.first_name %> <%= @guest.last_name %></p>
  <p>Email: <%= @guest.email %></p>
  <p>Allocated Seats: <%= @guest.alloted_seats %></p>
  <p>Committed Seats: <%= @guest.commited_seats %></p>


  <%= form_for @guest, url: { action: :update_commited_seats } do |f| %>
    <div class="field">
      <%= f.label :commited_seats %>
      <%= f.number_field :commited_seats %>
    </div>
    <div class="actions">
      <%= f.submit 'Update Commited Seats' %>
    </div>
  <% end %>

  <% flash.each do |key, value| %>
    <div class="flash-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  

<% else %>
  <p>Invalid RSVP link</p>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render "form", guest: @guest %>

<br>

<div>
  <%# link_to "Show this guest", @guest %>
  <%= link_to "Show this guest", [@event, @guest] %> |
  <%# link_to "Back to guests", guests_path %>
  <%= link_to "Back to guests", event_guests_path(@event) %>
</div>

app/views/guests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Guests</h1>

<div id="guests">
  <% @guests.each do |guest| %>
    <%= render guest %>
    <p>
      <%# link_to "Show this guest", guest %>
      <%= link_to "Show this guest", [@event, guest] %>
    </p>
  <% end %>
</div>

<%# link_to "New guest", new_guest_path %>
<%= link_to "New guest", new_event_guest_path(@event) %>

<%= link_to "Back to event", event_path(@event) %>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render "form", guest: @guest %>

<br>

<div>
  <%# link_to "Back to guests", guests_path %>
  <%= link_to "Back to guests", event_guests_path(@event) %>
</div>

app/views/guests/show.html.erb
<div style="margin-bottom: 20px;">
  <p style="color: green; font-size: 16px; font-weight: bold;"><%= notice %></p>
</div>

<div>
  <% @guests.each do |guest| %>
    <div style="margin-bottom: 15px; padding: 10px; border: 1px solid #ddd; border-radius: 5px;">
      <h3 style="margin-top: 0; color: #333;">
        <%= guest.first_name %> <%= guest.last_name %> - <%= guest.email %>
        <!-- Add other guest attributes you want to display -->
      </h3>
      
      <div style="margin-top: 10px;">
        <%= link_to "Edit this guest", edit_event_guest_path(@event, guest), class: "btn", style: "background-color: green; color: white; margin-right: 10px;" %>
        <%= button_to "Destroy this guest", event_guest_path(@event, guest), method: :delete, data: { confirm: "Are you sure?" }, class: "btn", style: "background-color: green; color: white;" %>
      </div>
    </div>
  <% end %>
</div>

<div style="margin-top: 20px;">
  <%= link_to "Back to event", event_path(@event), class: "btn btn-link", style: "margin-right: 15px;" %>
  <%= link_to "Add New Guest", new_event_guest_path(@event), class: "btn", style: "background-color: green; color: white;" %>
</div>