config/routes.rb
Rails.application.routes.draw do
  get 'token/exchange'
  get 'remember_me/clear_remember_me'
  get '/book_seats/:rsvp_link', to: 'guests#book_seats', as: 'book_seats'
  get '/email_services/new_email_template', to: 'email_services#new_email_template', as: 'new_email_template'
  get '/email_services/email_template/:id', to: 'email_services#edit_email_template', as: 'edit_email_template'
  get '/email_services/render_email_template', to: 'email_services#render_template', as: 'render_email_template'
  get 'destroy_email_template/:id', to: 'email_services#destroy_email_template', as: 'destroy_email_template'

  #get '/referral/:ref_code', to: 'referrals#refer', as: 'referral'

  get '/refer_a_friend/:random_code', to: 'referrals#new', as: 'new_referral'
  post '/refer_a_friend/:random_code', to: 'referrals#referral_creation', as: 'referral_creation'

  get '/buy_tickets', to: 'tickets#new', as: 'new_ticket_purchase'

  resources :email_services do
    member do
      get 'send_email'
      #get 'show'
      #get 'index'
    end
  end

  resources :events do
    resources :referrals, only: [:new, :referral_creation, :edit, :update]
  end

  resources :tickets, only: [:new, :create]

  post '/import_guests_csv', to: 'guests#import_guests_csv'# Defines a route for the upload_existing_plan action on guests controller.

  resources :guests do
    collection do
      post '/import_guests_csv', to: 'guests#import_guests_csv'
      get :import
      post :import, to: 'guests#process_import'
      get :new_guest, to: 'guests#new_guest'
    end
  end
  
  resources :events do
    resources :guests do
      collection do
        post 'import_csv', to: 'guests#import_guests_csv', as: 'import_csv'
      end
    end
  end

  
  root 'home#index'

  post 'email_services/add_email_template', to: 'email_services#add_email_template', as: 'add_email_template'
  patch '/email_services/email_template/:id/update', to: 'email_services#update_email_template', as: 'update_email_template'
  patch '/update_commited_seats/:rsvp_link', to: 'guests#update_commited_seats', as: 'update_commited_seats'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
    post 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
  end

  resources :events do
    resources :seats
    resources :guests
  end

  #resources :seats
  #resources :guests
end

app/models/event.rb
class Event < ApplicationRecord
    mount_uploader :event_avatar, AvatarUploader
    mount_uploader :event_box_office, SpreadsheetUploader
    belongs_to :user 
    # <!--===================-->
    # <!--to add nested scaffold-->
    has_many :seats , dependent: :destroy
    has_many :guests , dependent: :destroy
    has_many :email_services, dependent: :destroy
    has_many :referrals, dependent: :destroy
    # <!--===================-->
    def calculate_seating_summary(event_id)
        seating_summary = []
    
        Seat.where(event_id: event_id).each do |seat|
          guests_in_category = Guest.where(event_id: event_id, category: seat.category)
          committed_seats = guests_in_category.sum(:commited_seats)
          allocated_seats = guests_in_category.sum(:alloted_seats)
          total_seats = seat.total_count
    
          seating_summary << {
            category: seat.category,
            guests_count: guests_in_category.count,
            committed_seats: committed_seats,
            allocated_seats: allocated_seats,
            total_seats: total_seats
          }
        end
    
        seating_summary
      end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = current_user.events
  end

  # GET /events/1 or /events/1.json
  def show
    # <!--===================-->
    # <!--to show the uploaded spreadsheet-->
    @event = current_user.events.find(params[:id])
    @category = @event.seats.pluck(:category).uniq
    if @event.event_box_office.present?
      @event_box_office_data = []
      # Load the spreadsheet using the SpreadsheetUploader
      event_box_office_file = @event.event_box_office.current_path
      # Parse the contents of the event_box_office_file using Roo
      event_box_office_xlsx = Roo::Spreadsheet.open(event_box_office_file)
      event_box_office_xlsx.each_row_streaming do |row|
      # event_box_office_xlsx.each_row_streaming(max_rows: 2) do |row|
        row_data = []
        row.each { |cell| row_data << cell.value }
        @event_box_office_data << row_data
    end

      @referral_data = Referral.where(event_id: @event.id)

      email_index = 0
      tickets_index = 0
      amount_index = 0
      l = @event_box_office_data.first.length 
      for k in 0...l 
        if @event_box_office_data.first[k] == 'Email'
             email_index = k
        elsif @event_box_office_data.first[k] == 'Tickets'
             tickets_index = k         
        elsif @event_box_office_data.first[k] == 'Amount'
             amount_index = k
        end
      end
     
      @event_box_office_data.drop(1).each do |datum|
          @referral_data.each do |referraldatum|
             if referraldatum.referred == datum[email_index]
                referraldatum.update(status: true, tickets: datum[tickets_index], amount: datum[amount_index])                
             end
          end
      end

    else
      flash[:notice] = "No box office spreadsheet uploaded for this event"
      @event_box_office_data = []
    end

    @guests = @event.guests
    @seats = Seat.where(event_id: @event.id)
    @seating_summary = calculate_seating_summary(@event.id)
    @guest_details = Guest.where(event_id: @event.id)
    @referral_data = Referral.where(event_id: @event.id)   
    # <!--===================-->
  end

  # GET /events/new
  def new
    @event = current_user.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def calculate_seating_summary(event_id)
      seating_summary = []
    
      Seat.where(event_id: event_id).each do |seat|
        guests_in_category = Guest.where(event_id: event_id, category: seat.category)
        committed_seats = guests_in_category.sum(:commited_seats)
        allocated_seats = guests_in_category.sum(:alloted_seats)
        total_seats = seat.total_count
    
        seating_summary << {
          category: seat.category,
          guests_count: guests_in_category.count,
          committed_seats: committed_seats,
          allocated_seats: allocated_seats,
          total_seats: total_seats
        }
      end
    
      seating_summary
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.events.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      # params.require(:event).permit(:title, :address, :description, :datetime, :last_modified)
      
      
      # <!--===================-->
      # <!--to add upload field-->
      # params.require(:event).permit(:title, :address, :description, :datetime, :last_modified, :event_avatar)
      params.require(:event).permit(:title, :address, :description, :datetime, :last_modified, :event_avatar, :event_box_office)
      # <!--===================-->
      
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<!--===================-->
<!--event.last_modified is deleted since rails provide such information by default-->


<div id="<%= dom_id event %>">
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= event.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Datetime:</strong>
    <%= event.datetime %>
  </p>


  
  <!--===================-->
  <!--to add upload field-->
  <p>
    <strong>Event Avatar:</strong>
    <%= event.event_avatar %>
  </p>
  <p>
    <strong>Event Box Office:</strong>
    <%= event.event_box_office %>
  </p>
  <!--===================-->
  
  
  
  <!--===================-->
  <!--to give more info (these two come with every model)-->
  <p>
    <strong>Created at:</strong>
    <%= event.created_at %>
  </p>
  <p>
    <strong>Updated at:</strong>
    <%= event.updated_at %>
  </p>
  <!--===================-->
</div>

app/views/events/_form.html.erb
<!--===================-->
<!--event.last_modified is deleted since rails provide such information by default-->

<div class="form-box" style="width: 400px; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 10px;">
<%= form_with(model: @event,local: true, multipart: true) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" style="margin-bottom: 20px;">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control', style: 'width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 5px;' %>
  </div>

  <div class="form-group" style="margin-bottom: 20px;">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class: 'form-control', style: 'width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 5px;' %>
  </div>

  <div class="form-group" style="margin-bottom: 20px;">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: 'form-control', style: 'width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 5px;' %>
  </div>

  <div class="form-group" style="margin-bottom: 20px;">
    <%= form.label :datetime, style: "display: block" %>
    <%= form.datetime_field :datetime, class: 'form-control', style: 'width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 5px;' %>
  </div>
  
  
  <!--===================-->
  <!--to add upload field-->
  <div class="form-group" style="margin-bottom: 20px;">
    <%= form.label :event_avatar, style: "display: block" %>
    <%= form.file_field :event_avatar, class: 'form-control-file', style: 'width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 5px;' %>
  </div>
  
  <div class="form-group" style="margin-bottom: 20px;">
    <%= form.label :event_box_office, style: "display: block" %>
    <%= form.file_field :event_box_office, class: 'form-control-file', style: 'width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 5px;' %>
  </div>
  <!--===================-->
  
  
  <div class="actions">
    <%= form.submit 'Create / Edit', class: 'btn btn-primary', style: 'background-color: #007bff; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;' %>
  </div>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-5">
  <h1 class="display-3 text-center animated slideInLeft mb-5">Manage Events</h1>
  <!-- <img src="https://via.placeholder.com/300" class="img-fluid mt-4 animated slideInRight" alt="Placeholder Image"> -->
  <div class="description mt-5  mb-5 animated slideInRight">
    <p class="display-6">
      Here you can easily create, view, edit, and delete your events, allowing you to keep track of all your event-related activities.
    </p>
  </div>
</div>

<div style="text-align: center;">
  <%= link_to "Create New Event", new_event_path, class: "btn btn-primary", style: "margin-bottom: 20px; display: inline-block;" %>

  <div id="events">
    <% @events.each do |event| %>
      <div class="event-box" onclick="window.location.href='<%= event_path(event) %>'">
        <h2><%= event.title %></h2>
        <p><strong>Date:</strong> <%= event.datetime %></p>
        <p><strong>Description:</strong> <%= event.description %></p>
      </div>
    <% end %>
  </div>
</div>

<style>
  .event-box {
    border: 1px solid #ccc;
    border-radius: 10px; /* Rounded borders */
    padding: 10px;
    margin-bottom: 10px;
    cursor: pointer;
    width: 400px; /* Set the desired width for event boxes */
    display: inline-block; /* Display event boxes side by side */
    transition: transform 0.3s ease; /* Smooth transition for transform property */
  }

 .event-box:hover {
    background-color: #f5f5f5; /* Background color on hover */
    transform: translateY(-5px); /* Move the box up by 5 pixels */
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add shadow effect */
 }

  .btn {
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
  }

  .btn:hover {
    background-color: #0056b3;
  }
</style>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<style>
  .highlight-heading {
    background-color: #333; /* or any other dark grey color you prefer */
    color: #fff; /* text color for better visibility */
  }
</style>

<p style="color: green"><%= notice %></p>



<div class="container">
  <div class="row">
    <div class="col-md-6">
      <!-- Event Details -->
      <h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Event Details</h2>
      <h3 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 36px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);"><%= @event.title %></h3>
      <p style="margin-left:20%;margin-bottom:20px;margin-top:10px; font-size: 16px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);"><strong>Date:</strong> <%= @event.datetime %></p>
      <p style="margin-left:20%;margin-bottom:20px;margin-top:10px; font-size: 16px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);"><strong>Description:</strong> <%= @event.description %></p>
      <p style="margin-left:20%;margin-bottom:20px;margin-top:10px; font-size: 16px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);"><strong>Address:</strong> <%= @event.address %></p>
      <div>
        <%= link_to "Edit", edit_event_path(@event), class: "btn btn-primary", style: "width: 200px;margin-left:20%;margin-bottom:20px;margin-top:10px;" %>
        <%= button_to "Delete", @event, method: :delete, class: "btn btn-danger", style: "width: 200px;margin-left:20%;margin-bottom:20px;margin-top:10px;" %>
      </div>
    </div>

    <!-- Image Section -->
    <div class="col-md-6">
      <% if @event.event_avatar.file.present? %>
        <img class="d-block mx-lg-auto img-fluid w-100 rounded shadow" src='<%= @event.event_avatar.url %>'
             alt='Event image' width="400" height="400" loading="lazy">
      <% end %>
    </div>
  </div>
</div>




<!--===================-->
<!--to display nested children-->
<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Manage Seating Levels</h2>
<div class="container">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="highlight-heading">
        <th>Category</th>
        <th>Section</th>
        <th>Total Count</th>
        <th>Edit Seat</th>
      </tr>
    </thead>
    <tbody>
      <% @seats.each do |seat| %>
        <tr>
          <td><%= seat[:category] %></td>
          <td><%= seat[:section] %></td>
          <td><%= seat[:total_count] %></td>
          <td><%= link_to 'Edit', edit_event_seat_path(@event, seat), style: 'display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;', class: 'button' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'Add New Seat', new_event_seat_path(@event), style: 'display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;margin-left:25%;margin-bottom:30px', class: 'button' %>


<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Seating Summary</h2>
<!--to add link for the nested children-->
<div class="container">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="highlight-heading">
        <th>Category</th>
        <th>Number of Guests</th>
        <th>Total Seats</th>
        <th>Allocated Seats</th>
        <th>Committed Seats</th>
        <th>Remaining Seats</th>
      </tr>
    </thead>
    <tbody>
      <% @seating_summary.each do |category| %>
        <tr>
          <td><%= category[:category] %></td>
          <td><%= category[:guests_count] %></td>
          <td><%= category[:total_seats] %></td>
          <td><%= category[:allocated_seats] %></td>
          <td><%= category[:committed_seats] %></td>
          <td><%= category[:total_seats] - (category[:committed_seats]) %></td> 
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  // Function to update the total count based on the selected section in Seating Summary
  $(document).on('change', '.section-dropdown', function() {
    var selectedSection = $(this).val();
    var totalSeats = 0;
    $('#seating-summary-table tbody tr').each(function() {
      if ($(this).find('td:nth-child(2)').text() === selectedSection) {
        totalSeats += parseInt($(this).find('td:nth-child(4)').text());
      }
    });
    $('#total-count').text(totalSeats);
  });
</script>


<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Manage Invited Guests</h2>
<!--to add link for the nested children-->
<div class="container">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="highlight-heading">
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Affiliation</th>
        <th>Category</th>
        <th>Section</th>
        <th>Allocated seat</th>
        <th>Committed seats</th>
        <th>Status</th>
        <th>Edit guest</th>
        <th>Destroy guest</th>
      </tr>
    </thead>
    <tbody>
      <% @guest_details.each do |guest| %>
        <tr>
          <td><%= guest[:first_name] %></td>
          <td><%= guest[:last_name] %></td>
          <td><%= guest[:email] %></td>
          <td><%= guest[:affiliation] %></td>
          <td><%= guest[:category] %></td>
          <td><%= guest[:section] %></td>
          <td><%= guest[:alloted_seats] %></td>
          <td><%= guest[:commited_seats] %></td>
          <td><%= guest[:status] %></td>
          <td><%= link_to 'Edit', edit_event_guest_path(@event, guest), style: 'display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %></td>
          <td><%= button_to "Destroy", event_guest_path(@event, guest), method: :delete, data: { confirm: "Are you sure?" }, class: "btn", style: "display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div style="margin-left: 0%;">
<div style="margin-left: 25%; margin-bottom: 30px;">
  <%= link_to 'Add Guest', new_event_guest_path(@event), style: 'display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>

  <%= form_tag import_csv_event_guests_path(@event), multipart: true, style: 'display: inline-block;' do %>
    <%= file_field_tag 'file', id: "file-upload", style: "display: none;", onchange: "submitForm()" %>
    <%= hidden_field_tag :event_id, @event.id %>
  
    <button type="button" onclick="document.getElementById('file-upload').click()" class="btn btn-primary" style="display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer">
      Upload File
    </button>
  <% end %>
  
  <script>
    function submitForm() {
      var fileInput = document.getElementById('file-upload');
      if(fileInput.value) {
        fileInput.form.submit();
      }
    }
  </script>
  

</div>
<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Box Office Sales</h2>
<strong>Notification (!): Please upload .xlsx file having column names exactly 'Email', 'Tickets' and 'Amount', among other chosen columns, otherwise the corresponding data cannot be 
reflected correctly in the following referral table, causing eventually mistakes on the reward calculation and other considerations. We clarify further that the corresponding 'Tickets' means the quantity
of the tickets bought, and 'Amount' means on the other hand the total payment made for the tickets from the person for this event.</strong>
<% if @event_box_office_data.present? %>
<div class="container">
<table class="table table-striped table-hover">
  <thead>
    <tr class="highlight-heading">
      <% @event_box_office_data.first.each do |cell| %>
        <th><%= cell %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @event_box_office_data.drop(1).each do |row| %>
      <% unless row.nil? %>
      <tr>
        <% if row.respond_to?(:each) %>
          <% row.each do |cell| %>
            <td><%= cell %></td>
          <% end %>
        <% else %>
          <td><%= row %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>

<% else %>
  <p>No box office spreadsheet uploaded for this event.</p>
<% end %>

<!--to be added-->
<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Manage Referrals</h2>
<div class="container">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="highlight-heading">
        <th>Email</th>
        <th>Name</th>
        <th>Referred</th>
        <th>Status</th>
        <th>Tickets</th>
        <th>Amount($)</th>
        <th>Input Reward</th>
        <th>Rewards($)</th>
        <th>Calculation</th>
      </tr>
      <% @referral_data.each do |referraldatum| %>
       <tr>
        <td><%= referraldatum.email %></td>
        <td><%= referraldatum.name %></td>
        <td><%= referraldatum.referred %></td>
        <td><%= referraldatum.status %></td>
        <td><%= referraldatum.tickets %></td>
        <td><%= referraldatum.amount %></td>
        <td><%= referraldatum.reward_input %></td>
        <td><%= referraldatum.reward_value %></td>
        <td><%= link_to 'Calculate', edit_event_referral_path(@event, referraldatum) %></td>
       </tr>
      <% end %>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  // Function to update the total count based on the selected section in Seating Summary
  $(document).on('change', '.section-dropdown', function() {
    var selectedSection = $(this).val();
    var totalSeats = 0;
    $('#seating-summary-table tbody tr').each(function() {
      if ($(this).find('td:nth-child(2)').text() === selectedSection) {
        totalSeats += parseInt($(this).find('td:nth-child(4)').text());
      }
    });
    $('#total-count').text(totalSeats);
  });
</script>