config/routes.rb
Rails.application.routes.draw do
  get 'token/exchange'
  get 'remember_me/clear_remember_me'
  get '/book_seats/:rsvp_link', to: 'guests#book_seats', as: 'book_seats'
  get '/email_services/new_email_template', to: 'email_services#new_email_template', as: 'new_email_template'
  get '/email_services/email_template/:id', to: 'email_services#edit_email_template', as: 'edit_email_template'
  get '/email_services/render_email_template', to: 'email_services#render_template', as: 'render_email_template'
  get 'destroy_email_template/:id', to: 'email_services#destroy_email_template', as: 'destroy_email_template'

  #get '/referral/:ref_code', to: 'referrals#refer', as: 'referral'

  get '/refer_a_friend/:random_code', to: 'referrals#new', as: 'new_referral'
  post '/refer_a_friend/:random_code', to: 'referrals#referral_creation', as: 'referral_creation'

  get '/buy_tickets', to: 'tickets#new', as: 'new_ticket_purchase'

  resources :email_services do
    member do
      get 'send_email'
      #get 'show'
      #get 'index'
    end
  end

  resources :events do
    resources :referrals, only: [:new, :referral_creation, :edit, :update]
  end

  resources :tickets, only: [:new, :create]

  post '/import_guests_csv', to: 'guests#import_guests_csv'# Defines a route for the upload_existing_plan action on guests controller.

  resources :guests do
    collection do
      post '/import_guests_csv', to: 'guests#import_guests_csv'
      get :import
      post :import, to: 'guests#process_import'
      get :new_guest, to: 'guests#new_guest'
    end
  end
  
  resources :events do
    resources :guests do
      collection do
        post 'import_csv', to: 'guests#import_guests_csv', as: 'import_csv'
      end
    end
  end

  
  root 'home#index'

  post 'email_services/add_email_template', to: 'email_services#add_email_template', as: 'add_email_template'
  patch '/email_services/email_template/:id/update', to: 'email_services#update_email_template', as: 'update_email_template'
  patch '/update_commited_seats/:rsvp_link', to: 'guests#update_commited_seats', as: 'update_commited_seats'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'oauth/authorize', to: 'users/authorizelogin#authorize_event360'
    get 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
    post 'auth/events360/callback', to: 'users/omniauth_callbacks#events360'
  end

  resources :events do
    resources :seats
    resources :guests
  end

  #resources :seats
  #resources :guests
end

app/models/email_service.rb
class EmailService < ApplicationRecord
   
    #attr_accessible :email_template_id, :to, :subject, :body, :event_id, :guest_id
    belongs_to :event, optional: true
    belongs_to :guest, optional: true
end

app/controllers/email_services_controller.rb
class EmailServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_email_service, only: %i[ show edit update destroy ]

  
  # <!--===================-->
  # <!--to add mailing service-->
  def send_email
    email_service = EmailService.find(params[:id])
    event = Event.find(email_service.event_id)
    guest = Guest.find(email_service.guest_id)

    #full_url = ENV['localhost:3000'].to_s + book_seats_path(guest.rsvp_link)
    full_url = "https://eventnxt24-3eb21df1cc32.herokuapp.com/" + book_seats_path(guest.rsvp_link)
    #full_url = "http://127.0.0.1:3000/" + book_seats_path(guest.rsvp_link)
    print full_url
    
    #the referral link takes the form of '/refer_a_friend?:ref_code'.
    #params[:ref_code] = guest.id will be the parameter value to be used.
    #we have the referral link takes the form of '/refer_a_friend?guest.id' to transfer the parameters.
    #random_code_generated = SecureRandom.hex(20)

    referral_url = Rails.application.routes.url_helpers.new_referral_url(host: 'localhost:3000', random_code: guest.rsvp_link)
    
    #referral_url = ENV['localhost:3000'].to_s + new_referral_path(guest.id)

    updated_body = email_service.body.gsub("PLACEHOLDER_LINK", referral_url)
    
    ApplicationMailer.send_email(email_service.to, email_service.subject, updated_body, event, guest, full_url).deliver_later
    
    flash[:success] = 'Email sent!'
    email_service.update(sent_at: Time.current)
    redirect_to email_services_url
  end
  
  # <!--===================-->
  
  
  # GET /email_services or /email_services.json
  def index
    #puts ("------------------------------")
    @email_services = EmailService.all
    #puts("In index controller");
    
    # <!--===================-->
    # <!--to filter emails based on their sent_at status-->
    @sent_emails = EmailService.where.not(sent_at: nil) # Get all sent emails
    @unsent_emails = EmailService.where(sent_at: nil) # Get all unsent emails
    @email_templates = EmailTemplate.all
    # <!--===================-->
  end

  # GET /email_services/1 or /email_services/1.json
  def show
    #puts("****************")
    #puts("reached here")
    @email_service = EmailService.find(params[:id])
    #puts(@email_service)
    #puts("****************")
    render :show 
  end

  # GET /email_services/new
  def new
    @email_service = EmailService.new
    
    # <!--===================-->
    # <!--to have access to another model-->
    @events = Event.all
    # <!--===================-->
  end

  # GET /email_services/1/edit
  def edit
  end

  # POST /email_services or /email_services.json
  def create
    @email_service = EmailService.new(email_service_params)
    puts email_service_params

    respond_to do |format|
      if @email_service.save
        format.html { redirect_to email_services_url, notice: "Email service was successfully created." }
        format.json { render :show, status: :created, location: @email_service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @email_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_services/1 or /email_services/1.json
  def update
    respond_to do |format|
      if @email_service.update(email_service_params)
        format.html { redirect_to email_service_url, notice: "Email service was successfully updated." }
        format.json { render :show, status: :ok, location: @email_service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @email_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_services/1 or /email_services/1.json
  def destroy
    @email_service.destroy

    respond_to do |format|
      format.html { redirect_to email_services_url, notice: "Email service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_email_template
    render '_form_email_template'
  end
  
  def add_email_template

    email_template_params = params.permit(:name, :subject, :body)
    @email_templates = EmailTemplate.new(email_template_params)
  
    respond_to do |format|
      if @email_templates.save
        format.html { redirect_to email_services_url, notice: 'Email template was successfully created.' }
      else
        format.html { render '_form_email_template', alert:  'Error: Email template could not be saved.'}
      end
    end
  end

  def edit_email_template
    @email_template = EmailTemplate.find(params[:id])
    render '_edit_email_template'
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'Email template not found' }, status: :not_found
  end 

  def update_email_template
    @email_template = EmailTemplate.find(params[:id])
    email_template_params = params.require(:email_template).permit(:name, :subject, :body)
  
    puts "I'm here"
  
    if @email_template.update(email_template_params)
      redirect_to email_services_url, notice: 'Email template was successfully updated.'
    else
      render '_edit_email_template', alert: 'Error: Email template could not be saved.'
    end
  end
  

  def render_template
    email_template = EmailTemplate.find(params[:id])

    respond_to do |format|
      format.json do
        render json: { subject: email_template.subject, body: email_template.body }
      end
    end
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'Email template not found' }, status: :not_found
  end

  def destroy_email_template
    @email_template = EmailTemplate.find(params[:id])
    @email_template.destroy

    respond_to do |format|
      format.html { redirect_to email_services_url, notice: 'Email template was successfully deleted.' }
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Email template not found' }, status: :not_found
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_service
      @email_service = EmailService.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def email_service_params
      # params.require(:email_service).permit(:to, :subject, :body)
      # params.require(:email_service).permit(:to, :subject, :body, :sent_at, :committed_at)
      # params.require(:email_service).permit(:to, :subject, :body, :sent_at, :committed_at, :event_id)
      params.require(:email_service).permit(:email_template_id,:to, :subject, :body, :sent_at, :committed_at, :event_id, :guest_id)
    end

    
end

app/helpers/email_services_helper.rb
module EmailServicesHelper
end

app/views/email_services/_edit_email_template.html.erb
<h1>Edit Template</h1>

<div class="form-box" style="width: 400px; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 10px;">
<%= form_with(model: @email_template, url: { controller: "email_services", action: "update_email_template", id: @email_template }, method: :patch, local: true) do |f| %>
    <div class="field" style="margin-top: 10px;">
      <%= f.label :name, class: "form-label" %><br />
      <%= f.text_field :name, autofocus: true, style: "color: black; font-family: 'Times New Roman', Times, serif;", value: @email_template.name %>
    </div>

    <div class="field" style="margin-top: 10px;">
      <%= f.label :subject, class: "form-label" %><br />
      <%= f.text_field :subject, autofocus: true, style: "color: black; font-family: 'Times New Roman', Times, serif;", value: @email_template.subject %>
    </div>

    <div class="field" style="margin-top: 10px;">
      <%= f.label :body, class: "form-label" %><br />
      <%= f.text_area :body, autofocus: true, style: "color: black; font-family: 'Times New Roman', Times, serif; width: 200px; height: 100px;", value: @email_template.body %>
    </div>

    <div class="details-container">
      <%= f.submit "Update Template", class: "btn btn-primary rounded-3", style: "background-color: #f0f0f0; color: black; font-family: 'Times New Roman';" %>
    </div>
  <% end %>
</div>

app/views/email_services/_email_service.html.erb
<div id="<%= dom_id email_service %>">
  <p>
    <strong>To:</strong>
    <%= email_service.to %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= email_service.subject %>
  </p>
  
  
  <!--===================-->
  <!--to give more info about the emails-->
  <p>
    <strong>drafted at:</strong>
    <%= email_service.created_at %> |
    <strong>updated at:</strong>
    <%= email_service.updated_at %> |
    <strong>sent at:</strong>
    <%= email_service.sent_at %> |
    <strong>commited at:</strong>
    <%= email_service.committed_at %> |
    <strong>Event Name:</strong>
    <%= email_service.event ? email_service.event.title : "No Event" %>
  </p>
  <!--===================-->
  
  
  <p>
    <strong>Body:</strong>
    <%= email_service.body %>
  </p>
</div>

app/views/email_services/_email_template.html.erb
<style>
  .highlight-heading {
    background-color: #333; /* or any other dark grey color you prefer */
    color: #fff; /* text color for better visibility */
  }

  .small-body-container {
    width: 800px; /* Set the width */
    height: 100px; /* Maintain aspect ratio */
    border: 1px solid #ccc;
    overflow: auto; /* Add overflow to allow scrolling if content is larger */
  }


</style>

<% if @errors.present? %>
  <div class="alert alert-danger">
    <p><%= @errors %></p>
  </div>
<% end %>


<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Email Templates Summary</h2>
<div class="container">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="highlight-heading">
        <th>Template Name</th>
        <th>Subject</th>
        <th>Body</th>
        <th>Update Template</th>
        <th>Delete Template</th>
      </tr>
    </thead>
    <% if @email_templates && !@email_templates.empty? %>
      <tbody>
        <% @email_templates.each do |email_template| %>
          <tr>
            <td><%= email_template[:name] %></td>
            <td><%= email_template[:subject] %></td>
            <td>
              <div class="small-body-container">
                <%= email_template[:body].html_safe %>
              </div>
            </td>
            <td>
              <%= link_to 'Edit', edit_email_template_path(email_template.id), style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
            <td>
              <%= link_to 'Delete', destroy_email_template_path(email_template), method: :delete, style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

<%= link_to 'Add New Template', new_email_template_path, style: 'display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;margin-left:25%;margin-bottom:30px', class: 'button' %>

app/views/email_services/_form.html.erb
<head>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<style>
  .input-field {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  .form-box {
    width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
  }

  .form-label {
    display: block;
  }

  .form-control {
    width: 200px;
    height: 40px;
  }

  .form-group {
    margin-bottom: 0px; /* Adjust the margin between form groups */
  }
</style>

<div class="form-box">
  <%= form_with(model: email_service) do |form| %>
    <% if email_service.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(email_service.errors.count, "error") %> prohibited this email_service from being saved:</h2>
        <ul>
          <% email_service.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :event_id, class: "form-label" %>
      <%= form.select :event_id, options_for_select([[" ", nil]] + Event.all.map { |e| [e.title, e.id] }) %>
    </div>

    <div class="form-group">
      <%= form.label :guest_id, class: "form-label" %>
      <%= form.select :guest_id, options_for_select([[" ", nil]] + Guest.all.map { |g| ["#{g.first_name} #{g.last_name}", g.id] }) %>
    </div>

    <div class="form-group">
      <%= form.label :email_template_id, "Select Email Template", class: "form-label" %>
      <%= select_tag :email_template_id, options_for_select(EmailTemplate.pluck(:name, :id)), prompt: "Select an Email Template", class: "form-control", style: "width: 200px; height: 40px;", id: "email_template_select" %>
    </div>

    <div class="form-group">
      <%= form.label :to, class: "form-label" %>
      <%= form.text_field :to %>
    </div>

    <div class="form-group">
      <%= form.label :subject, class: "form-label" %>
      <%= form.text_field :subject, id: "email_subject" %>
    </div>

    <div class="form-group">
      <%= form.label :body, class: "form-label" %>
      <%= form.text_area :body, id: "email_body", style: "width: 200px; height: 100px;" %>
    </div>

    <div class="form-group">
      <%= form.submit %>
    </div>
  <% end %>

  <script>
    $(document).ready(function () {
      console.log("Document is ready.");

      $('#email_template_select').change(function () {
        console.log("Dropdown change event triggered.");

        var selectedTemplateId = $(this).val();

        $.get('/email_services/render_email_template', { id: selectedTemplateId }, function (data) {
          console.log("AJAX request successful.");
          $('#email_subject').val(data.subject);
          $('#email_body').val(data.body);
        });
      });
    });
  </script>
</div>

app/views/email_services/_form_email_template.html.erb
<h1>New Template</h1>

<div class="form-box" style="width: 400px; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 10px;">
  <%= form_with(model: @email_template, url: { controller: "email_services", action: "add_email_template" }, local: true) do |f| %>
    <div class="field" style="margin-top: 10px;">
      <%= f.label :name, class: "form-label" %><br />
      <%= f.text_field :name, autofocus: true, value: '', style: "color: black; font-family: 'Times New Roman', Times, serif;" %>
    </div>

    <div class="field" style="margin-top: 10px;">
      <%= f.label :subject, class: "form-label" %><br />
      <%= f.text_field :subject, autofocus: true, style: "color: black; font-family: 'Times New Roman', Times, serif;" %>
    </div>

    <div class="field" style="margin-top: 10px;">
      <%= f.label :body, class: "form-label" %><br />
      <%= f.text_area :body, autofocus: true, style: "color: black; font-family: 'Times New Roman', Times, serif; width: 200px; height: 100px;" %>
    </div>

    <div class="details-container">
      <%= f.submit "Create New template", class: "btn btn-primary rounded-3", style: "background-color: #f0f0f0; color: black; font-family: 'Times New Roman';" %>
    </div>
  <% end %>
</div>

app/views/email_services/edit.html.erb
<h1>Editing email service</h1>

<%= render "form", email_service: @email_service %>

<br>

<div>
  <%= link_to "Show this email service", @email_service %> |
  <%= link_to "Back to email services", email_services_path %>
</div>

app/views/email_services/index.html.erb
<style>
  .highlight-heading {
    background-color: #333; /* or any other dark grey color you prefer */
    color: #fff; /* text color for better visibility */
  }

  .small-body-container {
    width: 600px; /* Set the width */
    height: 100px; /* Maintain aspect ratio */
    border: 1px solid #ccc;
    overflow: auto; /* Add overflow to allow scrolling if content is larger */
  }

</style>
<p style="color: green"><%= notice %></p>

<h1>Email Service</h1>


<%= render 'email_template' %>
   

<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Unsent Email Services Summary</h2>
<div class="container">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="highlight-heading">
        <th>To</th>
        <th>Subject</th>
        <th>Body</th>
        <th>Send Email</th>
        <th>Edit Email</th>
        <th>Destroy Email</th>
      </tr>
    </thead>
    <% if @unsent_emails && !@unsent_emails.empty? %>
      <tbody>
        <% @unsent_emails.each do |email| %>
          <tr>
            <td><%= email[:to] %></td>
            <td><%= email[:subject] %></td>
            <td>
              <div class="small-body-container">
                <%= email[:body].html_safe %>
              </div>
            </td>
            <td>
              <%= link_to 'Send', send_email_email_service_path(email), style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
            <td>
              <%= link_to 'Edit', edit_email_service_path(email), style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
            <td>
              <%= link_to "Destroy", [email], method: :delete, style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

<%= link_to 'Add New Email', new_email_service_path(@event), style: 'display: inline-block; padding: 10px 20px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;margin-left:25%;margin-bottom:30px', class: 'button' %>


<h2 style="margin-left:20%;margin-bottom:20px;margin-top:40px; font-size: 56px; color: #333; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Sent Email Services Summary</h2>
<div class="container">
  <table class="table table-striped table-hover">
    <thead>
      <tr class="highlight-heading">
        <th>To</th>
        <th>Subject</th>
        <th>Body</th>
        <th>Re-Send Email</th>
        <th>Edit Email</th>
        <th>Destroy Email</th>
      </tr>
    </thead>
    <% if @sent_emails && !@sent_emails.empty? %>
      <tbody>
        <% @sent_emails.each do |email| %>
          <tr>
            <td><%= email[:to] %></td>
            <td><%= email[:subject] %></td>
            <td>
              <div class="small-body-container">
                <%= email[:body].html_safe %>
              </div>
            </td>
            <td>
              <%= link_to 'Send', send_email_email_service_path(email), style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
            <td>
              <%= link_to 'Edit', edit_email_service_path(email), style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
            <td>
              <%= link_to "Destroy", [email], method: :delete, style: 'display: inline-block; padding: 10px 10px; background-color: #4caf50; color: #fff; text-decoration: none; border: none; border-radius: 5px; cursor: pointer', class: 'button' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/email_services/index_original.html.erb
<p style="color: green"><%= notice %></p>

<h1>Email services</h1>

<%= link_to "New email service", new_email_service_path %>

<div id="email_services">
  <% @email_services.each do |email_service| %>
    <%= render email_service %>
    <p>
      <%= link_to "Show this email service", email_service %>
    </p>
  <% end %>
</div>

app/views/email_services/new.html.erb
<h1>New email service</h1>

<%= render "form", email_service: @email_service %>

<br>

<div>
  <%= link_to "Back to email services", email_services_path %>
</div>

app/views/email_services/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @email_service %>

<div>
  <%= link_to "Edit this email service", edit_email_service_path(@email_service) %> |
  <%= link_to "Back to email services", email_services_path %> |
  <%= link_to "Send the email", send_email_email_service_path(@email_service),
      method: :post, data: { "turbo-confirm": 'Are you sure?' } %>
  
  <%= button_to "Destroy this email service", @email_service, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
</div>